GOOGLE_CLIENT_ID = "227737251971-3vkntacvc81jk89l9ls70t5e7n3roaod.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
GOOGLE_REDIRECT_URL = "http://localhost:8501"

BACKEND_HOST = "https://avq-adapter-backend-e0b61a398552.herokuapp.com/"
BACKEND_CLIENT_ID = "l37OUiOZSJDM0zlwQjEUgrIkRb4iw9ACRO0Bhlnl"
BACKEND_CLIENT_SECRET = "y8JgaTbDswWGQzJwv5Uho0idbDnEPg7rXYrs2F2H8CkAnUJVt1wNMpsm7ToGIEljVELEjC2nza5RjggNzvTBNooEXIyf2v0sAzC8HKu50q81WAUFvgFEQTj0Ivxu7aik"