from dotenv import load_dotenv
from langchain import hub
from langchain.agents import AgentExecutor, create_openai_functions_agent
from langchain_community.chat_models.azure_openai import AzureChatOpenAI
from langchain_experimental.tools import PythonREPLTool

load_dotenv()

tools = [PythonREPLTool()]

instructions = """You are an agent designed to write and execute python code to answer questions.
You have access to a python REPL, which you can use to execute python code.
If you get an error, debug your code and try again.
Only use the output of your code to answer the question. 
You might know the answer without running any code, but you should still run the code to get the answer.
If it does not seem like you can write code to answer the question, just return "I don't know" as the answer.
"""

base_prompt = hub.pull("hwchase17/openai-functions-agent")
prompt = base_prompt.partial(instructions=instructions)

llm = AzureChatOpenAI(
    model="gpt-4o-East-US2",
    api_key="a096090373464949980ad13a8291afa3",
    api_version="2024-02-01",
    azure_endpoint="https://regioneastus2.openai.azure.com/",
    temperature=0.5)

agent = create_openai_functions_agent(llm, tools, prompt)

agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)

prompt = """You are an agent designed to answer answer queries based on dataframe records. You need to find the entries and make the computation and return it.


DATAFRAME:
```json
[
    {
        "question": "What is the company's total revenue?",
        "acronym": "Total Revenue",
        "full_name": "Total Revenue",
        "description": "Total revenue represents the total amount of income generated by the sale of goods or services related to the company's primary operations.",
        "found": 1,
        "value": "29,446",
        "source": 48
    },
    {
        "question": "What is the company's total equity?",
        "acronym": "Total Equity",
        "full_name": "Total Stockholders' Equity",
        "description": "Total equity represents the residual interest in the assets of the entity after deducting liabilities. It includes common stock, additional paid-in capital, retained earnings, accumulated other comprehensive income, and treasury stock.",
        "found": 1,
        "value": "13.2 billion USD",
        "source": 50
    },
    {
        "question": "What is the company's net income?",
        "acronym": "Net Income",
        "full_name": "Net Income",
        "description": "Net income is the total profit of a company after all expenses and taxes have been deducted from total revenue.",
        "found": 1,
        "value": "2,475 million",
        "source": 110
    },
    {
        "question": "What is the company's EBIT?",
        "acronym": "EBIT",
        "full_name": "Earnings Before Interest and Taxes",
        "description": "EBIT is a measure of a company's profitability that includes all expenses except interest and income tax expenses.",
        "found": 1,
        "value": "3,337 million",
        "source": 110
    },
    {
        "question": "What is the company's gross profit?",
        "acronym": "Gross Profit",
        "full_name": "Gross Profit",
        "description": "Gross profit is the difference between total revenue and the cost of goods sold (COGS). It represents the profit a company makes after deducting the costs associated with making and selling its products or the costs associated with providing its services.",
        "found": 1,
        "value": "9,710 million",
        "source": 110
    },
    {
        "question": "What are the company's cash flow from operations?",
        "acronym": "CFO",
        "full_name": "Cash Flow from Operations",
        "description": "Cash flow from operations represents the net cash generated from the company's core business activities.",
        "found": 1,
        "value": "1,287 million USD",
        "source": 112
    },
    {
        "question": "What is the cash and cash equivalents of the company?",
        "acronym": "CCE",
        "full_name": "Cash and Cash Equivalents",
        "description": "Cash and cash equivalents represent the company's most liquid assets, including cash on hand and short-term investments that are readily convertible to cash.",
        "found": 1,
        "value": "4,156",
        "source": 112
    },
    {
        "question": "What are the company's total assets?",
        "acronym": "Total Assets",
        "full_name": "Total Assets",
        "description": "Total assets represent the sum of all assets owned by a company, including current and non-current assets.",
        "found": 1,
        "value": "39,148 million USD",
        "source": 197
    },
    {
        "question": "What are the company's current liabilities?",
        "acronym": "Current Liabilities",
        "full_name": "Current Liabilities",
        "description": "Current liabilities are a company's debts or obligations that are due within one year.",
        "found": 1,
        "value": "15,568",
        "source": 197
    },
    {
        "question": "What are the inventories of the company?",
        "acronym": "Inventories",
        "full_name": "Inventories of the company",
        "description": "The value of the company's inventories, which includes raw materials, work-in-progress, and finished goods.",
        "found": 1,
        "value": "4,880 million USD",
        "source": 197
    },
    {
        "question": "What are the company's current assets?",
        "acronym": "Current Assets",
        "full_name": "Current Assets",
        "description": "Current assets are all the assets of a company that are expected to be sold, consumed, or used through standard business operations within one year.",
        "found": 1,
        "value": "19,570",
        "source": 197
    },
    {
        "question": "What are the company's cash flow from investing?",
        "acronym": "CFI",
        "full_name": "Cash Flow from Investing",
        "description": "Cash flow from investing activities represents the net cash used in or provided by a company's investing activities, such as purchases and sales of investments, property, plant, and equipment, and acquisitions or divestitures of businesses.",
        "found": 1,
        "value": "981",
        "source": 198
    },
    {
        "question": "What are the company's cash flow from financing?",
        "acronym": "CFF",
        "full_name": "Cash Flow from Financing",
        "description": "Cash flow from financing activities represents the net cash used or provided by a company's financing activities, including transactions involving debt, equity, and dividends.",
        "found": 1,
        "value": "-2,394 million (2022), -4,968 million (2021), -8,175 million (2020)",
        "source": 199
    }
]
````

Compute the ROE (Return on Equity) of the company based on the provided data. The formula for ROE is:

```
ROE = Net Income / Total Equity
```
"""

# agent_executor.invoke({"input": prompt})



if __name__ == "__main__":
    agent_executor.invoke({"input": prompt})